# Generated by Django 3.1 on 2021-07-25 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210725_2124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'Conta', 'verbose_name_plural': 'Contas'},
        ),
    ]
