# Generated by Django 3.1 on 2021-07-18 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_complement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='color',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='size',
        ),
    ]
